"""Local deterministic Topic -> ResearchResult -> Script orchestration."""

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from uuid import UUID, uuid5

from pydantic import ValidationError

from youtube_factory.application.exceptions import (
    ArtifactPersistenceError,
    IncompletePipelineError,
    ProviderContractError,
)
from youtube_factory.domain.models import ContentManifest, ResearchResult, Script, Topic
from youtube_factory.ports import ProjectArtifactStore, ResearchProvider, ScriptGenerator

PIPELINE_VERSION = "phase-1-local-v1"
_PROJECT_NAMESPACE = UUID("ffb67c5b-9e6f-46bd-aace-3f3a783d90b4")
_DETERMINISTIC_CREATED_AT = datetime(2026, 1, 1)


@dataclass(frozen=True, slots=True)
class CreateContentResult:
    """Artifacts generated by a successful content-foundation run."""

    project_id: UUID
    project_directory: Path
    topic: Topic
    research: ResearchResult
    script: Script
    manifest: ContentManifest


class CreateContentUseCase:
    """Coordinates ports while keeping CLI and adapters free of orchestration logic."""

    def __init__(
        self,
        research_provider: ResearchProvider,
        script_generator: ScriptGenerator,
        artifact_store: ProjectArtifactStore,
    ) -> None:
        self._research_provider = research_provider
        self._script_generator = script_generator
        self._artifact_store = artifact_store

    def execute(self, topic_title: str) -> CreateContentResult:
        """Create and persist deterministic research and script artifacts."""
        project_id = uuid5(_PROJECT_NAMESPACE, topic_title.strip())
        topic = Topic(id=project_id, title=topic_title, created_at=_DETERMINISTIC_CREATED_AT)
        research = self._research(topic)
        script = self._generate_script(topic, research)
        manifest = ContentManifest(
            project_id=project_id,
            pipeline_version=PIPELINE_VERSION,
            topic=topic.title,
            topic_id=topic.id,
            artifacts=("topic.json", "research.json", "script.json", "manifest.json"),
            research_provider=self._research_provider.identifier,
            script_generator=self._script_generator.identifier,
        )
        project_directory = self._persist(project_id, topic, research, script, manifest)
        return CreateContentResult(
            project_id=project_id,
            project_directory=project_directory,
            topic=topic,
            research=research,
            script=script,
            manifest=manifest,
        )

    def _research(self, topic: Topic) -> ResearchResult:
        try:
            research = ResearchResult.model_validate(self._research_provider.research(topic))
        except ValidationError as error:
            raise ProviderContractError("research provider returned an invalid contract") from error
        if research.topic_id != topic.id:
            raise ProviderContractError("research provider returned a result for a different topic")
        return research

    def _generate_script(self, topic: Topic, research: ResearchResult) -> Script:
        try:
            script = Script.model_validate(self._script_generator.generate(topic, research))
        except ValidationError as error:
            raise ProviderContractError("script generator returned an invalid contract") from error
        if script.topic_id != topic.id:
            raise ProviderContractError("script generator returned a script for a different topic")
        return script

    def _persist(
        self,
        project_id: UUID,
        topic: Topic,
        research: ResearchResult,
        script: Script,
        manifest: ContentManifest,
    ) -> Path:
        try:
            project_directory = self._artifact_store.save(
                str(project_id), topic, research, script, manifest
            )
        except ArtifactPersistenceError:
            raise
        except OSError as error:
            raise ArtifactPersistenceError("could not persist project artifacts") from error
        if not project_directory:
            raise IncompletePipelineError("artifact store did not return a project directory")
        return project_directory
