"""Validated domain models for the Shorts production pipeline."""

from youtube_factory.domain.models.contracts import (
    Asset,
    ContentManifest,
    Narration,
    NarrationGeneratorMetadata,
    RenderJob,
    RenderResult,
    ResearchProviderMetadata,
    ResearchResult,
    Scene,
    ScenePlan,
    ScenePlannerMetadata,
    Script,
    ScriptGeneratorMetadata,
    ShortProject,
    Source,
    TimedScenePlan,
    Topic,
    VisualAsset,
    VisualAssetGeneratorMetadata,
    VisualAssetManifest,
    VisualPrompt,
    VisualPromptPlan,
)

__all__ = [
    "Asset",
    "ContentManifest",
    "Narration",
    "NarrationGeneratorMetadata",
    "RenderJob",
    "RenderResult",
    "ResearchResult",
    "ResearchProviderMetadata",
    "Scene",
    "ScenePlan",
    "ScenePlannerMetadata",
    "Script",
    "ScriptGeneratorMetadata",
    "ShortProject",
    "Source",
    "TimedScenePlan",
    "Topic",
    "VisualAsset",
    "VisualAssetGeneratorMetadata",
    "VisualAssetManifest",
    "VisualPrompt",
    "VisualPromptPlan",
]
